call plug#begin($XDG_CONFIG_HOME."/plugged")


Plug 'rust-lang/rust.vim'
Plug 'neoclide/coc.nvim', {'do': { -> coc#util#install()}}
Plug 'Raimondi/delimitMate'
Plug 'tpope/vim-fugitive'
Plug 'kshenoy/vim-signature'
Plug 'vim-scripts/Mark--Karkat'
Plug 'scrooloose/nerdtree'
Plug 'easymotion/vim-easymotion'
Plug 'scrooloose/nerdcommenter'
Plug 'junegunn/vim-easy-align'
Plug 'Yggdroot/indentLine'
Plug 'vim-syntastic/syntastic'
Plug 'Chiel92/vim-autoformat'
Plug 'ryanoasis/vim-devicons'
Plug 'itchyny/lightline.vim'
Plug 'frazrepo/vim-rainbow'
Plug 'Yggdroot/LeaderF'

" TODO(lsl): if you can adapt tag function of leaderf, remove tagbar
" Plug 'majutsushi/tagbar'


call plug#end()


source $XDG_CONFIG_HOME/nvim/vimrcs/basic.vimrc
source $XDG_CONFIG_HOME/nvim/vimrcs/coc.vimrc
source $XDG_CONFIG_HOME/nvim/vimrcs/nerdtree.vimrc
source $XDG_CONFIG_HOME/nvim/vimrcs/easymotion.vimrc
source $XDG_CONFIG_HOME/nvim/vimrcs/nerdcommenter.vimrc
source $XDG_CONFIG_HOME/nvim/vimrcs/easy-align.vimrc
source $XDG_CONFIG_HOME/nvim/vimrcs/syntastic.vimrc
source $XDG_CONFIG_HOME/nvim/vimrcs/lightline.vimrc
source $XDG_CONFIG_HOME/nvim/vimrcs/autoformat.vimrc
source $XDG_CONFIG_HOME/nvim/vimrcs/rainbow.vimrc
source $XDG_CONFIG_HOME/nvim/vimrcs/leaderf.vimrc

" TODO(lsl): if you can adapt tag function of leaderf, remove tagbar
" source $XDG_CONFIG_HOME/nvim/vimrcs/tagbar.vimrc
